repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: bash -c 'out=$(git ls-files -z "*.go" | xargs -0 gofmt -l); if [ -n "$out" ]; then echo "$out"; exit 1; fi'
        language: system
        pass_filenames: false
      - id: go-test
        name: go test ./...
        entry: go test ./...
        language: system
        pass_filenames: false
